server:
  port: ${SERVER_PORT:8000}
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: pi
    password: pipass
  cloud.stream:
    rabbit:
      bindings:
        inputChannel:
          consumer:
            bindQueue: false
            declareExchange: false
            missingQueuesFatal: true
            queueNameGroupOnly: true
        outputChannel:
          producer:
            bindQueue: false
            declareExchange: false
            routing-key-expression: "'update_message'"
    bindings:
      outputChannel:
        destination: topic.update.message
        binder: rabbit
      inputChannel:
        group: queue.update.message
        binder: rabbit