server:
  port: ${SERVER_PORT:8000}
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: pi
    password: pipass
  cloud.stream:
    rabbit:
      bindings:
        inputChannel:
          consumer:
            missingQueuesFatal: true
            bindingRoutingKey: data_change
            exchangeAutoDelete: false
        outputChannel:
          producer:
            bindingRoutingKey: data_change
            routing-key-expression: "'data_change'"
            exchangeAutoDelete: false
    bindings:
      outputChannel:
        requiredGroups: consumer_group
        destination: update.message.exchange
        binder: rabbit
      inputChannel:
        group: consumer_group
        destination: update.message.exchange
        binder: rabbit