version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: pi
      RABBITMQ_DEFAULT_PASS: pipass
    ports:
      - "5672:5672"
      - "15672:15672"